### ISSUE TITLE
[BUG] Fondo del menú principal desajustado

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#117]
**Descripción**
El fondo aplicado en la escena no se muestra de forma correcta.

**Pasos**
Pasos para reproducir el error:
1. Acceder al menú principal desde el menú de registro.

**Comportamiento esperado**
El fondo debería estar ajustado al lienzo y ser _responsive_.

**Capturas**
![image](https://user-images.githubusercontent.com/43931833/141122239-35eab387-c1f5-48c8-9acb-819b86dc0959.png)

**Comment by Requena21** [comment]
Solución del BUG:

El escalado no funcionaba con sprites así que he decidido crear botones que no son interactuables y que si se escalan con la pantalla. Estos botones se ponen el primero en la jerarquía para que sean renderizados al fondo y se puedan ver el resto de botones.
