### ISSUE TITLE
[INV] Menú de instrucciones permanente

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#118]
**Descripción**
El panel de instrucciones del videojuego se muestra de forma permanente en la pantalla (desde un inicio), impidiendo la interacción con la mayor parte de la pantalla.

**Comportamiento esperado**
Este panel solo debería mostrarse antes de jugar al videojuego que le toque al jugador.

**Capturas**
![image](https://user-images.githubusercontent.com/43931833/141139999-5f0bfa65-013d-4208-a7ac-0fa9b49af1f2.png)

**Comment by kalomano** [comment]
Ya se solucionó, el problema es que todavía no estaba implementado
