### ISSUE TITLE
[INV] Calidad de imagen

### ISSUE THREAD

**Issue by rox06io** [VRSDevs/XO-Rivals#149]
**Descripción**
El juego no se ve full HD, pierden mucha calidad los sprites 

**Comportamiento esperado**
Mejora de la calidad de los elementos para crear una experiencia correcta

**Capturas**
Forma esperada de ver el juego
![Esperado](https://user-images.githubusercontent.com/72705329/141373829-a3a400ba-abc4-44f7-ac67-bd6bf323540d.png)
Forma en la que se ve
![Actual](https://user-images.githubusercontent.com/72705329/141373944-303dbf15-281a-4068-a0f8-69ddbad64c9b.png)

**Comment by Requena21** [comment]
Primer intento de solución:

- Se ha cambiado la resolución de todos los sprites de 2048 a 16384.
- Se ha cambiado la calidad de gráficos a ultra como predeterminada.

**Comment by Requena21** [comment]
En este punto no se encuentra una solución mejor y nos quedamos por el momento con los cambios comentados en el comentario anterior.
