### ISSUE TITLE
[BUG - USB][ALT] El sonido del juego sigue tras apagar el móvil o salir del navegador

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#344]
**Descripción**
Tras salir del navegador o apagar el móvil, el sonido del juego sigue reproduciéndose.

**Impacto**
- Alto.

**Plataforma**
- Móvil (Chrome y Firefox).

**Pasos**
Pasos para reproducir el error:
1. Abrir juego
2. Salir del navegador / Apagar el dispositivo.

**Comment by AlberVicky09** [comment]
https://stackoverflow.com/questions/63707032/unity3d-webgl-mute-the-sound-when-tab-or-browser-inactive
