### ISSUE TITLE
[BUG - USB][BAJ] Barras de sonido función incorrecta

### ISSUE THREAD

**Issue by Requena21** [VRSDevs/XO-Rivals#345]
**Descripción**
En la barras de sonido, tanto de Sfx como de Musica, no hay cambios en el volumen a partir  de la mitad de la barra hacia la derecha. Quizás cambiar los valores máximos y mínimos del Slider lo pueda solucionar.

**Impacto**
- Bajo

**Plataforma**
- Todas las plataformas

**Pasos**
Pasos para reproducir el error:
1. Ir a login.
2. Ir a settings.
3. Subir sliders a más del 50%.
4. Ver error.

**Comportamiento esperado**
El slider funcionando correctamente con cualquier valor.

**Comment by AlberVicky09** [comment]
https://forum.unity.com/threads/volume-slider-not-working.811992/
