### ISSUE TITLE
[BUG - OTR][MED] Rotación del jugador en el fantasmas

### ISSUE THREAD

**Issue by Requena21** [VRSDevs/XO-Rivals#347]
**Descripción**
En el minijuego "Ghost Hunter" el personaje controlado por el jugador se queda rotando continuamente . Es posible que esto suceda porque el rigidbody del gameobject del  gameobject del jugador tenga el "angular drag" a 0 o cercano a 0.

**Impacto**
- Medio.

**Plataforma**
- Todas.

**Pasos**
Pasos para reproducir el error:
1. Jugar partida.
2. Jugar minijuego de los fantasmas.
3. Chocar con un obstáculo.
4. Ver error.

**Comportamiento esperado**
Jugador no rota al colisionar.

**Comment by kalomano** [comment]
Además de solucionar el problema e implementado un funcionamiento correcto.
No rota con las paredes debido a que he bloqueado la rotación de sus físicas (en el script RigidBody de Player):
![freezeZ](https://user-images.githubusercontent.com/73484962/143782041-c815ef02-da42-4a95-9061-d51c45579d54.PNG)

En el movimiento del jugador he añadido un método que rota al personaje según su movimiento (usando unos cuaterniones que corresponden a la dirección de cada eje):

```
    private void rotarPersonaje()
    {
        //ARRIBA
        if (vertical == 1 && horizontal == 0)
        {
            transform.rotation = quatT;
        }
        //ABAJO
        if (vertical == -1 && horizontal == 0)
        {
            transform.rotation = quatB;
        }

        //ABAJO DERECHA
        if (vertical == -0.707107f && horizontal == 0.707107f)
        {
            transform.rotation = quatBR;
        }

        //ABAJO IZQUIERDA
        if (vertical == -0.707107f && horizontal == -0.707107f)
        {
            transform.rotation = quatBL;
        }

        //ARRIBA DERECHA
        if (vertical == 0.707107f && horizontal == 0.707107f)
        {
            transform.rotation = quatTR;
        }

        //ARRIBA IZQUIERDA
        if (vertical == 0.707107f && horizontal == -0.707107f)
        {
            transform.rotation = quatTL;
        }
        //DERECHA
        if (horizontal == 1 && vertical == 0)
        {
            transform.rotation = quatR;
        }

        //IZQUIERDA
        if (horizontal == -1 && vertical == 0)
        {
            transform.rotation = quatL;
        }
    }
```
