### ISSUE TITLE
[BUG - CNF][MED] Nombres con espacios en el login

### ISSUE THREAD

**Issue by Requena21** [VRSDevs/XO-Rivals#349]
**Descripción**
Si se introduce un nombre de usuario con un espacio, no funciona el registro y salen varios errores en la consola.

**Impacto**
- Medio.

**Plataforma**
- Todas.

**Pasos**
Pasos para reproducir el error:
1. Registro
2. Rellenar campo con algún espacio.
3. Pulsar enter.
4. Ver error.

**Comportamiento esperado**
Mensaje diciendo que no es una entrada válida o rellenar con guiones bajos los espacios.

**Comment by AlberVicky09** [comment]
No se puede meter espacios en los nombres de PlayFab
Hacemos un bucle que recorra el nombre y si hay espacios en blanco, diga nombre no valido. Hasta que no haya espacios en blanco, no permitimos que cree usuario en PlayFab
Codigo -> Char.IsWhiteSpace(char);

**Comment by Blinx24** [comment]
Finalmente, se ha incorporado un algoritmo que comprueba si existe algún espacio en blanco y muestra un mensaje al usuario de que su nombre o contraseña no puede contener espacios

En la clase [`Login.cs`](https://github.com/VRSDevs/XO-Rivals/blob/main/XO%20Rivals/Assets/Scripts/LoginMenu/Login.cs):
```
private bool ValidateInputs()
    {
        // Sin espacios
        if (_username.Contains(" ") || _password.Contains(" "))
        {
            //Decirle al jugador que no puede
            Log.text = "No whitespaces allowed";

            _isConnecting = false;
            return false;
        }
        
        ...
    }
```
