### ISSUE TITLE
[MEJ - USB][BAJ] Visión del jugador reducida en "Gravitational Jump"

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#352]
**Descripción**
En este minijuego, la única dirección posible es hacia adelante. Para darle una mayor visión al jugador, se podría ajustar la cámara para que muestre menos de lo que hay detrás del jugador.

**Impacto**
- Bajo.

**Plataforma**
- Todas las plataformas.

**Pasos**
Pasos para reproducir el error:
1. _Login_.
2. _Play_.
3. _Create Game_ y encontrar partida.
4. Jugar al minijuego _Gravitational Jump_.

**Comment by Requena21** [comment]
La jugabilidad está planteada para que el jugador tema la colisión de la cámara. Se podrían plantear otras características para el futuro.
