### ISSUE TITLE
[INV - USB][ALT] Visión del cronómetro de "Ghost Hunter"

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#353]
**Descripción**
El cronómetro no se ajusta al tamaño de la pantalla y el color de este hace que no se distinga bien en este minijuego.

**Impacto**
- Alto.

**Plataforma**
- Todas las plataformas.

**Pasos**
1. _Login_.
2. _Play_.
3. _Create game_ y encontrar partida.
4. Jugar a _Ghost Hunter_.

**Capturas**
![image](https://user-images.githubusercontent.com/43931833/143512015-86f67b2b-fbd7-40a7-a680-5774e68969f4.png)

**Comment by Requena21** [comment]
Como en el bug 353, el fallo era producido por el canvas scaler.

![image](https://user-images.githubusercontent.com/60947079/144094026-ffb667b6-0f39-4407-ac3f-f688d89f8317.png)
