### ISSUE TITLE
[MEJ - JUG][BAJ] Aleatorización de minijuegos predictiva

### ISSUE THREAD

**Issue by Requena21** [VRSDevs/XO-Rivals#359]
**Descripción**
La lista de minijuegos que aparece al finalizar uno no es aleatoria, si no que depende del minijuego que escojas. Eso puede permitir a los jugadores predecir que minijuegos le van a tocar

**Impacto**
- Bajo

**Plataforma**
- Todas

**Pasos**
Pasos para reproducir el error:
1. Login
2. Crear partida
3. Jugar minijuego cualquiera
4. Ver error al elegir minijuegos

**Comportamiento esperado**
La elección de minijuego debería ser totalmente aleatoria.

**Comment by AlberVicky09** [comment]
Es totalmente aleatorio, pero como solo hay 4 minijuegos por el momento, hay pocas opciones
