### ISSUE TITLE
[BUG - JUG][MED] Sonido de derrota se repite si eres tocado por varios fantasmas en "Ghost Hunter"

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#362]
**Descripción**
Si se pierde en dicho minijuego, ya habiendo perdido, los fantasmas puedn seguir detectando al jugador y tocándolo, haciendo que se repita el sonido varias veces.

**Impacto**
- Medio.

**Plataforma**
- Todas las plataformas.

**Pasos**
Pasos para reproducir el error:
1. _Login_.
2. _Play_.
3. Crear sala.
4. Seleccionar minijuego _Ghost Hunter_.
5. Perder el minijuego.

**Sugerencia**
Quizás, si se hace al jugador no interaccionable con los fantasmas se arregle el error.

**Comment by kalomano** [comment]
Error solucionado en el pull #412 

```
   if (!gameEnded)
            {
                gameEnded = true;
                Invoke("VictoryCanvas", 1f);
            }
```
```
 if(!gameEnded)
                {
                    gameEnded = true;
                    Invoke("DefeatCanvas", 0.2f);
                }
```
