### ISSUE TITLE
[BUG - OTR][ALT] No aparecen las salas creadas a otros usuarios

### ISSUE THREAD

**Issue by Requena21** [VRSDevs/XO-Rivals#363]
**Descripción**
No sé actualiza la ventana de current Matches tras crear una partida

**Impacto**
- Alto

**Plataforma**
- Todas

**Pasos**
Pasos para reproducir el error:
1. (Usuario 1 y 2)Login
2. (Usuario 1)Crear partida
3. (Usuario 2)No ve la partida para unirse

**Comportamiento esperado**
Deberían salir las salas al ser creadas para el resto de usuarios.

**Comment by Blinx24** [comment]
La funcionalidad principal de "_CurrentMatches_" es mostrar una lista de las partidas activas que tiene un jugador en concreto, por lo que esta funcionalidad no se implementará.

No obstante, se ha cambiado el mensaje de retroalimentación proporcionado al jugador cuando no tiene ninguna partida.
![image](https://user-images.githubusercontent.com/43931833/144600424-77e49984-02f7-436a-89ec-3ee9284bc070.png)
