### ISSUE TITLE
[INV - OTR][BAJ] **The Gunman** Se puede mantaner presionado hasta el infinito

### ISSUE THREAD

**Issue by Requena21** [VRSDevs/XO-Rivals#364]
**Descripción**
El botón de disparo se puede mantener presionado hasta el infinito y no se acaba el minijuego

**Impacto**
- Bajo

**Plataforma**
- 

**Pasos**
Pasos para reproducir el error:
1. Login
2. Jugar partida
3. Jugar pistolero
4. Ver error.

**Comportamiento esperado**
El botón se desactiva cuando ha pasado demasiado tiempo

**Comment by kalomano** [comment]
No veo esto un error, si los demás opinan que si se puede implementar solución fácil avisando al jugador que tardó demasiado.
