### ISSUE TITLE
[INV- OTR][BAJ] Al refrescar la pagina (F5), una vez dentro del juego, se queda en negro tras dar al botón "Go!" (no sale el logo de Virtual Ravens en Grande)

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#365]
**Descripción**
Ya habiendo dado al botón de _Run Game_ de itch.io, si se refresca la página, hay veces que no se muestra la pantalla para ver el logo de la empresa.

**Impacto**
- Bajo.

**Plataforma**
- PC (Chrome y Firefox).

**Pasos**
Pasos para reproducir el error:
1. _Run Game_.
2. F5.
3. Pulsar botón _GO!_.

**Comment by Requena21** [comment]
No soy capaz de reproducir este error.

**Comment by Requena21** [comment]
Se ha creado la animación directamente con el sistema que proporciona unity.
