### ISSUE TITLE
[BUG - CNF][CRT] No puedes jugar la primera vez que entras al juego

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#368]
**Descripción**
Cuando entras al juego, te permite registrarte con una cuenta nueva y te sale que estás conectado. Pero no ocurre nada, no entras al juego ni nada, te quedas en esa pantalla. Si te sales de ahí y le das a “_Login_”, aparece que la cuenta que acabas de crear no existe. Tienes que salirte del juego y volver a cargar la pestaña para que el juego reconozca tu cuenta y puedas jugar.

**Impacto**
- Crítico.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. _Register_.
2. Crear cuenta.
3. _Login_.
4. Entrar con la cuenta nueva.

**Comment by AlberVicky09** [comment]
Puede que esto lo arregle, es que llames al login directamente despues de registrar
https://community.playfab.com/questions/14414/new-created-users-cant-login-but-they-are-register.html

**Comment by Blinx24** [comment]
Este fallo estaba relacionado directamente con la configuración del servidor.

Se han cambiado algunos ajustes de _Photon_ y finalmente ya permite realizar el registro e iniciar sesión al mismo tiempo, sin quedarse bloqueado y obligando al usuario a recargar la página.
