### ISSUE TITLE
[INV - USB][MED] El menú al que se accede al darle a “Play” es muy confuso.

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#371]
**Descripción**
El menú al que se accede al darle a “Play” en el menú de inicio es increíblemente confuso y no se entiende como funciona. Hasta que no has jugado muchísimas partidas no se entiende que en el cuadro de “_Current Matches_” aparecen partidas dejadas a medias, sobre todo porque en ningún momento se te da a entender que puedas dejar una partida a la mitad (esto se aprendió por error.
Pensábamos que si te salías de una partida perdías automáticamente). Por este motivo, el botón de “_Join_” parece que sobra y no tiene ningún sentido hasta que descubres ese detalle. En general es una pantalla increíblemente confusa, porque como en ningún momento se explica al jugador cómo funciona (que puedes dejar una partida a medias, y que puedes retomarla luego si quieres), parece que todo sobra y te pierdes muchísimo.

**Impacto**
- Media.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. _Play_ en el menú principal.

**Comment by Requena21** [comment]
Posible solución: La primera partida de un jugador sería guiada con un tutorial. Al entrar se le iría guiando por los menús para que jugase su primera partida. Al jugar esa partida,(Puede ser ficticia) se le explica el sistema de lista de partidas. Es algo que hacen otros juegos de este estilo.

**Comment by Requena21** [comment]
Se han actualizado los botones y ahora hay más menús para que quede todo más claro.
