### ISSUE TITLE
[INV - USB][BAJ] Cambio de significado de los botones de la esquina superior izquierda

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#372]
**Descripción**
En el juego, todos los menús tienen el mismo diseño, más específicamente, tienen tres botones en la barra superior: uno rojo, uno amarillo y uno verde. Dependiendo de en qué menú estés, estos botones realizan una acción diferente (por ejemplo, en el menú de inicio, el botón rojo es para cerrar tu sesión, pero durante una partida es para rendirte en la partida). Si estos botones se
mantienen iguales en todos los menús (mismo color, tamaño y colocación), deberían tener el mismo significado siempre.

**Impacto**
- Bajo.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. Avanzar por los menús.
2. Fijarse en los botones en la barra superior

**Capturas**
![image](https://user-images.githubusercontent.com/43931833/143511628-65d7126f-3f4b-44bf-a26f-1f00c9157aae.png)
![image](https://user-images.githubusercontent.com/43931833/143511638-59994f98-1b64-4304-bd77-914849da2ea7.png)

**Comment by Requena21** [comment]
No creemos que esto sea un problema ya que los símbolos indican la funcionalidad de cada botón.
