### ISSUE TITLE
[MEJ - USB][BAJ] Cuadro de confirmación al realizar una acción sin retorno

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#373]
**Descripción**
Cuando te rindes en una partida, o cuando le das a cerrar sesión debería aparecerte un cuadro de confirmación, ya que es una acción irreversible y puede que le hayas dado sin querer (o que cambies de opinión). Son acciones muy importantes, cuyas consecuencias no se pueden deshacer.

**Impacto**
- Baja.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. Pulsar el botón rojo de la barra superior de los menús, independientemente si es rendirse o cerrar sesión.

**Comment by kalomano** [comment]
Sería necesario crear un panel para comfirmar si estás seguro (equipo de arte). Implementarlo sería cambiar las acciones de los botones.

**Comment by Requena21** [comment]
Se han creado advertencias en las acciones de estos botones.
