### ISSUE TITLE
[INV - JUG][MED] En el minijuego “Ghost Hunter”, los controles indicados no son correctos

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#374]
**Descripción**
La pantalla que te explica el minijuego “_Ghost Hunter_” te indica en la parte inferior los controles para este juego. Los controles para ordenador son incorrectos. Además de usar la tecla A y la tecla D, también se usa la tecla W y la tecla S.

**Impacto**
- Media.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. Jugar al minijuego "_Ghost Hunter_".

**Capturas**
![image](https://user-images.githubusercontent.com/43931833/143511954-d62843e6-faf4-4e6a-9d31-2ad885564d2d.png)

**Comment by Requena21** [comment]
Ya se ha actualizado el canvas donde no estabán los botones de subir y bajar.

![image](https://user-images.githubusercontent.com/60947079/144094264-fe88fe59-bcfe-45fc-b723-7a18654a863f.png)
