### ISSUE TITLE
[BUG - JUG][BAJ] El temporizador del minijuego “Ghost Hunter” aumenta en vez de disminuir

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#375]
**Descripción**
Si el minijuego cuenta con un temporizador y su mecánica es sobrevivir una cierta cantidad de tiempo, el tiempo debería disminuir no aumentar. Que el tiempo aumente resulta muy confuso, y eso hace que el juego no se entienda del todo bien.

**Impacto**
- Bajo.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. Jugar al “_Ghost Hunter_” (en ordenador, pues en el móvil no aparece el temporizador).

**Comment by kalomano** [comment]
Debido a que se plantea modificar este juego drásticamente dejo estos cambios para el final.

**Comment by kalomano** [comment]
Cambios realizados en el linked pull request.
