### ISSUE TITLE
[INV - USB][MED] En el minijuego “Ghost Hunter” la tecla para ir hacia arriba está colocada abajo

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#376]
**Descripción**
En el minijuego “Ghost Hunter”, en los controles para el móvil el botón para mover al avatar hacia arriba está colocada por debajo de otras teclas, como moverse hacia la derecha. Es muy poco intuitivo y confunde muchísimo. Si es la tecla para ir hacia arriba, debería estar arriba.

**Impacto**
- Medio.

**Plataforma**
- Móvil.

**Pasos**
Pasos para reproducir el error:
1. Jugar al “Ghost Hunter” en el móvil.

**Capturas**
![image](https://user-images.githubusercontent.com/43931833/143512323-3ca49d23-e5e0-4989-baac-0a11067fed2a.png)

**Comment by Requena21** [comment]
Los botones ya han sido colocados correctamente.

![image](https://user-images.githubusercontent.com/60947079/144104696-001ee82a-8517-49ce-9dcd-0fac1c9b6d5a.png)
