### ISSUE TITLE
[BUG - CNF][IMP] En el minijuego “Ghost Hunter” si te pegas mucho a una pared te quedas pillado

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#377]
**Descripción**
En el minijuego “Ghost Hunter” si te pegas mucho a una pared, el avatar se queda pillado y no puedes moverte. Debes retroceder perpendicular a la pared un poquito para poder seguir moviéndote.

**Impacto**
- Bajo.

**Plataforma**
- Móvil.

**Pasos**
Pasos para reproducir el error:
1. Jugar al “_Ghost Hunter_”.
2. Pegarte todo lo posible a una pared.
3. Luego intentar moverte sin separarte de la pared.

**Comment by kalomano** [comment]
No me ocurre este error, es probable que se haya solucionado al solucionar el error por el cual el personaje rotaba con las paredes en el pull #408; también es posible que no lo haya podido reproducir correctamente.

**Comment by kalomano** [comment]
El error parece haber sido solucionado.
