### ISSUE TITLE
[MEJ - JUG][BAJ] En el minijuego “Ghost Hunter” si te quedas parado en una esquina puedes ganar siempre

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#378]
**Descripción**
En el minijuego “Ghost Hunter” si te vas a una esquina del laberinto y te quedas ahí parado ganas siempre. No hace falta que hagas nada, pues los fantasmas no te persiguen y es muy probable que ni se acerquen a ti.

**Impacto**
- Bajo.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. Jugar al “_Ghost Hunter_”.

**Comment by kalomano** [comment]
Solucionado al cambiar el objetivo del minijuego
