### ISSUE TITLE
[BUG - CNF][ALT] En el minijuego “Gravitational Jumps” te puedes quedar pillado entre dos plataformas.

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#379]
**Descripción**
En el minijuego “_Gravitational Jumps_” si te caes entre dos plataformas que están muy juntas el avatar del jugador se queda ahí pillado y no puedes hacer nada. Si esto ocurre el juego no reconoce que has muerto, ni siquiera cuando el scroll lateral de la pantalla sobrepasa al avatar. El scroll lateral continúa hasta que has superado incluso la posición de la bandera, y un poco más allá (hasta que el fondo no son más que estrellas, sin planetas). Solo en ese momento reconoce que has muerto y te aparece la pantalla de derrota.

**Impacto**
- Alto.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. Jugar al minijuego “_Gravitational Jumps_”.
2. Caerte entre dos plataformas que estén cerca.

**Capturas**
![image](https://user-images.githubusercontent.com/43931833/143512781-ec4127ff-07c2-41fa-ac58-2c8c8e2e9e20.png)

**Comment by Requena21** [comment]
He propuesto la solución de poner un collider que mate al jugador si pasa un tiempo encerrado. La mejor solución será mejorar la distancia entre plataformas mediante beta testing.

![image](https://user-images.githubusercontent.com/60947079/144099484-44241a04-a103-4a3a-b8b2-26e32619a99c.png)
