### ISSUE TITLE
[BUG - CNF][BAJ] En el minijuego “Cooking with me” a veces no funciona el movimiento del personaje

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#381]
**Descripción**
En el minijuego “_Cooking with me_”, si presionas el botón de movimiento hacia el sentido contrario al que te estabas moviendo muy rápido, el avatar deja de moverse. Es decir, si te estás moviendo hacia la derecha con la tecla D, y cambias a la tecla A muy rápido (por que quieres hacer un cambio de dirección), el avatar deja de moverse. Al cambiar de izquierda a derecha pasa lo mismo. Este
problema se soluciona dejando de pulsar la nueva tecla y volviendo a pulsarla, pero aún así es muy molesto.

**Impacto**
- Bajo.

**Plataforma**
- Ordenador.

**Pasos**
Pasos para reproducir el error:
1. Jugar al minijuego “_Cooking with me_”.
2. Moverte hacia una dirección.
3. Cambiar de dirección muy rápido.

**Comment by Requena21** [comment]
Se ha solucionado el movimiento comprobando si el jugador mantenía la tecla pulsada mientras pulsaba otro botón y no solo comprobando si la tecla es pulsada en ese instante.
![image](https://user-images.githubusercontent.com/60947079/144778271-b10e67d9-6fd3-4068-a287-c11736f3e520.png)
