### ISSUE TITLE
[BUG- CNF][CRT] El minijuego “Cooking with me” no funciona para el jugador que ha creado la partida

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#382]
**Descripción**
Si eres el jugador que ha creado la sala (el primero en darle a “_New Game_”), el minijuego “_Cooking with me_” no te funciona. Te aparece todo correctamente, pero los controles para móvil no funcionan y no te puedes mover, por lo que no puedes jugar y pierdes siempre.

**Impacto**
- Crítico.

**Plataforma**
- Móvil.

**Pasos**
Pasos para reproducir el error:
1. Ser el jugador que crea la sala (en el móvil).
2. Jugar al minijuego “_Cooking with me_”.

**Comment by Requena21** [comment]
El bug se ha solucionado adjudicando en el editor los métodos de movimiento del personaje a los botones.

![image](https://user-images.githubusercontent.com/60947079/144092400-fd51296e-f423-4e84-9afb-44eb6631301c.png)
