### ISSUE TITLE
[MEJ - BAL][MED] En el minijuego “Cooking with me” podrías tener más tiempo

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#383]
**Descripción**
En el minijuego “_Cooking with me_” podrías tener más tiempo, pues el tiempo disponible es demasiado poco para poder completar este juego. Teniendo en cuenta que tienes que seguir una receta concreta, y que además te penalizan si te equivocas, con tan poco tiempo es casi imposible pasárselo.

**Impacto**
- Medio.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. Jugar al minijuego “_Cooking with me_”.

**Comment by rox06io** [comment]
Perdería la gracia de la partida al volverse más lento el juego.
