### ISSUE TITLE
[MEJ - BAL][IMP] En el minijuego “Cooking with me” puede no aparecer en ningún momento uno de los ingredientes, por lo que no te lo puedes pasar

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#384]
**Descripción**
En el minijuego “_Cooking with me_” puede ocurrir que durante una partida no te aparezca en ningún momento alguno de los ingredientes que necesitas. Sin todos los ingredientes no puedes completar el juego, por lo que si el juego no te da como mínimo uno de cada, es imposible completar este minijuego.

**Impacto**
- Alto.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. Jugar al minijuego “_Cooking with me_”.

**Comment by Requena21** [comment]
Se ha aumentado la cadencia de caida de alimentos. Esto hace más dificil esquivar y además es más probable que caigan todos los alimentos necesarios.
