### ISSUE TITLE
[BUG- JUG][MED] En el minijuego “The Gunman” no se entiende que a partir de los 3 segundos dejará de aparecer el tiempo

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#385]
**Descripción**
Al minijuego “_The Gunman_” le falta un poco de explicación. No es nada intuitivo que a partir de los 3 segundo el tiempo desaparece y tú debes seguir la cuenta en tu cabeza. Como salen guiones, parece que el juego ha sufrido un error o que el contador ha llegado a 0 de golpe. Teniendo en cuenta que todos los minijuegos cuentan con una pantalla de explicación previa, podría indicarse allí.

**Impacto**
- Medio.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. Jugar al minijuego “_The Gunman_”.

**Comment by kalomano** [comment]
Plantearía cambiar la descripción
