### ISSUE TITLE
[MEJ - JUG][BAJ] Solo hay 4 minijuegos

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#388]
**Descripción**
El juego solo cuenta con 4 minijuegos, y todos muy simples. En el transcurso de una partida normal te toca repetir el mismo minijuego unas cuantas veces, y si juegas más de una partida más de lo mismo. Resulta muy repetitivo y aburrido al cabo de un tiempo.

**Impacto**
- Bajo.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. Jugar una partida.

**Comment by Requena21** [comment]
Se ha creado uno nuevo y hay más pensados para hacer.
