### ISSUE TITLE
[INV - USB][MED] Deberías poder bajar el volumen de la música desde el principio

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#390]
**Descripción**
El juego empieza con una música muy alta, pero no puedes bajarle el volumen hasta que has iniciado sesión (o en el peor de los casos, hasta que te has registrado y luego iniciado sesión). Es bastante tiempo con un volumen de música altísimo que no puedes bajar.

**Impacto**
- Medio.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. Abrir el juego (no vale que cierres sesión, pues se guarda tu configuración del sonido).

**Comment by Requena21** [comment]
La solución más plausible es la de mantener un volumen medio/bajo al entrar al juego.

**Comment by Nachete07** [comment]
Se ha iniciado la musica desde el main menu en vez desde el menu de login para asi poder modificarlo una vez q empiece a sonar
