### ISSUE TITLE
[BUG - CNF][MED] La barra de sonido SFX no regula el volumen de todos los efectos de sonido

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#391]
**Descripción**
La barra de sonido SFX del menú de opción no regula el volumen de todos los efectos de sonido del juego. Por ejemplo, el efecto de sonido al pulsar “_New Game_” en el menú de “_Play_”, o el efecto de salto en el minijuego de “_Gravitational Jumps_” no se regulan. Siempre suenan al mismo volumen, aunque bajes la barra de sonido SFX al mínimo. (Puede que haya más efectos que suenen, pero solo hemos encontrado esos).

**Impacto**
- Medio.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. Entrar al menú de opción.
2. Silenciar el volumen de los efectos de sonido.
3. Ir al menú de “_Play_”.
4. Darle a “_New Game_”.
5. Jugar al minijuego “_Gravitational Jumps_”.

**Comment by Nachete07** [comment]
Se han asignado todos los sonidos de forma correcta para que puedan ser controlados desde la barra de soniods del menu de ajustes
