### ISSUE TITLE
[MEJ - JUG][BAJ] El jugador que no está jugando podría ver a su rival cuando juega a sus minijuegos, o podrían competir juntos

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#392]
**Descripción**
La jugabilidad del juego es un poco extraña. Mientras tu rival está jugando tú no puedes hacer nada, y no se te muestra nada por pantalla. Estaría bien poder ver como juega tu rival, o incluso poder competir en los minijuegos.

**Impacto**
- Bajo.

**Plataforma**
- Ordenador y móvil.

**Comment by kalomano** [comment]
No veo necesario solucionar este error al ser desatendido.
