### ISSUE TITLE
[BUG - CNF][BAJ] Empiezas el juego siendo nivel 3

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#393]
**Descripción**
Cuando te creas una cuenta nueva y entras al juego con ese usuario por primera vez, empiezas ya directamente siendo de nivel 3. Además, debajo hay una barra verde casi llena pero pone que llevas 0 de 100.

**Impacto**
- Bajo.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. Crearse un usuario nuevo.
2. Entrar al juego.
3. Seleccionar el ícono verde al lado de tu nombre de usuario
4. Ver error.

**Capturas**
![image](https://user-images.githubusercontent.com/43931833/143515209-b99f7a89-b5ad-468f-8159-b90143acede0.png)

**Comment by AlberVicky09** [comment]
Se me olvido cambiarlo al mandarlo, eran valores de prueba
