### ISSUE TITLE
[BUG - CNF][ALT] Los controles para móvil funcionan de manera incorrecta

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#394]
**Descripción**
Los controles para móvil funcionan de manera incorrecta a menudo. A veces no se pulsan, u otras veces quedan pulsados aún cuando levantas el dedo.

**Impacto**
- Alto.

**Plataforma**
- Móvil.

**Pasos**
Pasos para reproducir el error:
1. Jugar al juego en móvil.

**Comment by kalomano** [comment]
Es probable que los botones sean demasiado pequeños, Alejandro ya ha aumentado su tamaño, queda abierto el Issue igualmente
