### ISSUE TITLE
[INV - USB][ALT] Los botones de los controles para móvil son demasiado pequeños

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#395]
**Descripción**
Los botones de los controles para el móvil son demasiado pequeños, tanto que resulta casi imposible pulsarlos, y en determinados minijuegos (como el “_Ghost Hunter_”) puede ocurrir que pulses dos botones a la vez (por que son muy pequeños y están muy juntos). Jugar con estos controles es increíblemente incómodo, y hace que jugar sea bastante complicado.

**Impacto**
- Alto.

**Plataforma**
- Móvil.

**Pasos**
Pasos para reproducir el error:
1. Jugar al juego en móvil.

**Comment by Requena21** [comment]
Ya están los controles mejor adaptados en los minijuegos.

![image](https://user-images.githubusercontent.com/60947079/144106944-2034a137-3643-4c99-8ea7-3ad7a4a1fea7.png)

![image](https://user-images.githubusercontent.com/60947079/144105378-9db1d556-e20f-4ecc-8193-de714b0f5427.png)

![image](https://user-images.githubusercontent.com/60947079/144107208-5b0b4a29-9ad2-4e5f-9fc8-ac34d5363119.png)
