### ISSUE TITLE
[BUG - CNF][BAJ] Durante una partida, no se ve el nombre del otro jugador

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#396]
**Descripción**
Al comenzar una partida nueva, no te aparece el nombre del otro jugador en ningún momento.

**Impacto**
- Bajo.

**Plataforma**
- Móvil.

**Pasos**
Pasos para reproducir el error:
1. Jugar una partida en el móvil.

**Capturas**
![image](https://user-images.githubusercontent.com/43931833/143515808-d2ffde91-f713-4f97-92ac-e4b17003b67a.png)

**Comment by AlberVicky09** [comment]
Cuando el segundo jugador se une a la partida, deberia hacer un RPC que mande el nombre del O al X

**Comment by kalomano** [comment]
Ya debería tener el nombre, no tiene sentido que unas veces tenga el nombre y otras veces no, mi solución ha sido retrasar y repetir la asignación del texto hasta que se asigne correctamente, es probable que siga dando errores (a confirmar).
Pull #430 

```
public void Update()
    {
        if (nameO.text == "")
        {
            nameO.text = thisMatch.PlayerOName;
        }
        if (nameX.text == "")
        {
            nameX.text = thisMatch.PlayerXName;
        }
       
    }
```

**Comment by kalomano** [comment]
El último cambio parece haber solucionado el error
