### ISSUE TITLE
[BUG - CNF][BAJ] Durante una partida entera siempre pone que es mi turno

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#397]
**Descripción**
Durante una partida, en la parte superior de la pantalla siempre aparece que es mi turno, aunque esté jugando mi rival.

**Impacto**
- Bajo.

**Plataforma**
- Móvil.

*__NOTA:__ Este error solo nos ha ocurrido dos veces, por lo que no sabemos replicarlo.

**Comment by kalomano** [comment]
Solucionado en el pull request #411 
He usado la variable WhosTurn, faltaba usar correctamente esta variable y actualizarla correctamente
