### ISSUE TITLE
[MEJ - OTR][BAJ] Las vidas y su funcionamiento resultan confusas

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#400]
**Descripción**
Las vidas del juego y su funcionamiento resultan muy confusas. Pierdes una vida cuando empiezas una nueva partida, pero al acabar, ganes o pierdas, no te dan ninguna como recompensa. Estaría bien que perdieras una vida si pierdes la partida, o que te devuelvan una vida si ganas. Además, ganas una vida cada cierto tiempo hasta llegar al máximo que son 3 vidas. Pero cuando tienes 3
vidas y quieres consultarlo, te aparecen unas líneas que parecen un error del juego. Sería mejor si pusiera “__MAX__” o el contador a cero. Las líneas son confusas.

**Impacto**
- Bajo.

**Plataforma**
- Ordenador y móvil.

**Pasos**
Pasos para reproducir el error:
1. Jugar una partida.

**Capturas**
![image](https://user-images.githubusercontent.com/43931833/143516447-6409683b-99a7-41d4-8474-b82444bdce16.png)

**Comment by AlberVicky09** [comment]
Podriamos comentar en algun lado que el maximo de vidas es 3
