### ISSUE TITLE
[INV - CNF][BAJ] Puedes pulsar el botón amarillo cuando está inactivo

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#416]
**Descripción**
En la primera pantalla del juego, la del "_Login_" y en la pantalla del menú principal, el botón amarillo es presionable y hace un sonido, mientras que los demás no.

**Impacto**
- Bajo.

**Plataforma**
- PC / Móvil.

**Pasos**
Pasos para reproducir el error:
1. Menú "_Login_".
2. Pulsar el botón amarillo en la la primera pantalla y en menú principal.

**Comportamiento esperado**
El funcionamiento correcto sería que todos fuesen funcionales o preferiblemente que cuando no tiene nada que hacer que no sea funcional.

**Comment by Requena21** [comment]
Bug solucionado, se ha quitado la pista de audio y no tiene animación al ponerse encima de él.
