### ISSUE TITLE
[BUG] Fallo de minijuego pistolero al contar victoria y derrota.

### ISSUE THREAD

**Issue by Requena21** [VRSDevs/XO-Rivals#51]
**Descripción**
En algunos casos falla la detección de victoria y derrota y se notifica que se ha perdido la partida cuando se ha ganado.

**Pasos**
Pasos para reproducir el error:

En el juego si se obtiene un resultado muy cercano de 0 puede que notifique derrota al contar que el numero es igual a 0.

**Comportamiento esperado**
Notificar el resultado correcto de la partida.

**Capturas**
![image](https://user-images.githubusercontent.com/60947079/139563468-a65c6639-eb42-4d71-8444-ffe6e3fa5083.png)

**Comment by kalomano** [comment]
Solucionado en el pull #92, el problema no era que detectase erroneamente la derrota o victoria, sino que no aparecía correctamente el signo negativo (al obtener un tiempo menor que cero obtenías una derrota ) cuando el cronometro se paraba entre 0 y -1.

```

        decimas = Math.Abs(decimas);//el signo negativo solo tiene que estar en los segundos

        if (time < 0 && time > -1) //el signo negativo lo ponemos nosotros debido a que en los segundos no está (en las decimas si)
        {
            textoCrono.text = "-"+segundos + ":" + decimas;
        }
        else
        {
            textoCrono.text = segundos + ":" + decimas;
        }
```
