### ISSUE TITLE
[INV - CNF][BAJ] -  Puedes pulsar botones cuando están inactivos

### ISSUE THREAD

**Issue by FelipeBermejo** [VRSDevs/XO-Rivals#514]
**Descripción**
En la primera pantalla del juego, la del "Login" y en la pantalla del menú principal, el botón amarillo es presionable y hace un sonido, mientras que los demás no. También ocurre en la pantalla de créditos con el botón verde. Ese no suena, pero si que es interactuable.
  

**Impacto**
-  Bajo

**Plataforma**
-  Todas

**Pasos**
Pasos para reproducir el error:
1. Ir a al menú de "Login" y al menú principal
2. Hacer clic en el botón amarillo.
3. Ir al menú de "Créditos" 
4. Hacer clic en el botón verde. 

**Comportamiento esperado**
El funcionamiento correcto sería que todos fuesen funcionales o preferiblemente que cuando no tiene nada que hacer que no sea funcional.

**Capturas**
Incluir capturas del error.

**Información adicional**
Colocar aquí información adicional sobre el error.

**Comment by Requena21** [comment]
He modificado los botones que tenían este problema, pero es posible que haya alguno más.
