### ISSUE TITLE
[MEJ - USB][BAJ] Aviso de turno

### ISSUE THREAD

**Issue by FelipeBermejo** [VRSDevs/XO-Rivals#519]
**Descripción**
El feedback recibido al cambiar de turno es mínimo. Puedes no darte cuenta de que es tu turno.

**Impacto**
-  Bajo 

**Plataforma**
- Todas

**Pasos**
Pasos para reproducir el error:
1. Empezar una partida
2. Poner ficha en el tic-tac-toe y jugar el minijuego
3. Esperar tu turno
4. Tener el turno de vuelta

**Comportamiento esperado**
Una notificación o un aviso sería recomendable, pero alguna forma de feedback es necesaria.

**Comment by Requena21** [comment]
Se ha puesto un mensaje en grande en mitad del tablero con la información de quien es el turno.
