### ISSUE TITLE
[BUG - CMP][ALT]

### ISSUE THREAD

**Issue by FelipeBermejo** [VRSDevs/XO-Rivals#520]
**Descripción**
En el minijuego de los fantasmas, en el móvil, cuando te mueves hacia arriba y luego hacia algún lado, el movimiento se "bloquea" y no avanza el personaje.

**Impacto**
- Alto

**Plataforma**
- Móvil

**Pasos**
Pasos para reproducir el error:
1. Empezar una partida
2. Jugar al Ghost Hunter
3. Pulsar hacia arriba o hacia abajo e inmediatamente después pulsar derecha o izquierda

**Comportamiento esperado**
El jugador debería poder pulsar cualquier botón en cualquier orden y que el movimiento no se detenga

**Comment by Requena21** [comment]
Se ha solucionado haciendo que cuando se deje de pulsar un botón, solo se resetea la variable de velocidad de ese eje.
