### ISSUE TITLE
[MEJ - CMP][IMED] No puedo ver lo que escribo

### ISSUE THREAD

**Issue by FelipeBermejo** [VRSDevs/XO-Rivals#521]
**Descripción**
Cuando haces register o login en móvil, no puedes ver lo que estás escribiendo porque el teclado tapa lo que escribes. Esto se puede llegar a volver bastante incómodo. Te hace sentir perdido.

**Impacto**
- Medio

**Plataforma**
- Móvil

**Pasos**
Pasos para reproducir el error:
1. Ir al menú de login
2. Ir a registrarse o a Login
3. Escribir usuario o contraseña

**Comportamiento esperado**
Mientras escribes el usuario o la contraseña deberías poder ver lo que estás escribiendo

**Comment by Requena21** [comment]
Para poder escribir en móviles se ha usado un asset externo y por el momento no podemos editarlo.
