### ISSUE TITLE
[BUG - CNF][BAJ] El efecto de sonido de salto en el plataformas no suena con Pixyo

### ISSUE THREAD

**Issue by FelipeBermejo** [VRSDevs/XO-Rivals#524]
**Descripción**
Cuando juegas con Pixyo en el plataformas, el sonido de salto no suena  

**Impacto**
- Bajo

**Plataforma**
- Todas

**Pasos**
Pasos para reproducir el error:
1. Crear una partida y ser el host de la sala
2. Jugar al "Gravitational Jumps"
3. Usar el salto

**Comportamiento esperado**
El sonido de salto debería sonar cuando saltas da igual que personaje seas.

**Comment by Nachete07** [comment]
Se ha implementado el sonido al personaje de Pixyu al saltar
