### ISSUE TITLE
[INV - CNF][BAJ] El mensaje "Matchmaking Stopped" se solapa con el botón de "Private Game" 

### ISSUE THREAD

**Issue by FelipeBermejo** [VRSDevs/XO-Rivals#526]
**Descripción**
 En el menú de "Play" cuando cancelas una partida te sale en mensaje "Matchmaking stopped" y se solapa con el botón de "Private Game"

**Impacto**
-  Bajo

**Plataforma**
- Todas

**Pasos**
Pasos para reproducir el error:
1. Buscar una partida
2. Cancelar la búsqueda

**Comportamiento esperado**
Que no se solape el mensaje con el botón

**Comment by Blinx24** [comment]
Esto ya se solucionó desplazando los botones hacia los laterales.
