### ISSUE TITLE
[BUG] Retardo en algunos sonidos

### ISSUE THREAD

**Issue by Blinx24** [VRSDevs/XO-Rivals#60]
**Descripción**
Los sonidos implementados en el menú principal van con un poco de _delay_ al pulsar el botón.

**Comportamiento esperado**
Lo ideal sería que el sonido se pudiese escuchar en el mismo instante.

**Comment by Nachete07** [comment]
Se han modificado diferentes sonidos de manera externa para reducir el delay que tenían al reproducirse en el juego.
