### ISSUE TITLE
[BUG] Inicio simultáneo de jugadores

### ISSUE THREAD

**Issue by AlberVicky09** [VRSDevs/XO-Rivals#94]
**Descripción**
Al iniciar partida, ambos jugadores comienzan, de manera que el juego no es jugable

**Pasos**
Pasos para reproducir el error:
1. Ir a Menu Principal
2. Hacer clic en Crear Partida en un usuario y Unirse a Partida en otro
3. Ambos jugadores poseen el turno, de manera que una vez acaba el turno no pasa a nadie
4. Ver error.

**Comportamiento esperado**
Solo uno de los jugadores debería poder jugar al mismo tiempo

**Capturas**
![image](https://user-images.githubusercontent.com/61430785/140709295-481d6103-5a80-40dd-af18-c25021ebb7df.png)

**Información adicional**
El problema probablemente este en como se asigna el turno (el creador deberia ser la O y el que se une la X, pero probablemente funcione mal)

**Comment by kalomano** [comment]
Solución hecha para la beta, el problema pertenecía al código en la escena
